spring:
  application:
    name: trade-app
  datasource:
    url: "jdbc:mysql://localhost:3306/trade-app"
    username: user
    password: user-user1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB

server:
  port: 8081